# Gemfile for local Jekyll development
# To run locally: bundle install && bundle exec jekyll serve

source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-feed"
